### ISSUE TITLE
[Ubuntu] Chrome not working

### ISSUE THREAD

**Issue by mirkocomparetti-synesis** [marcusolsson/grafana-calendar-panel#17]
Hello,
The plugin does not work with grafana 7.5 if the user is not logged in (viewer only).
![image](https://user-images.githubusercontent.com/34926125/119334741-bfd7d080-bc8b-11eb-9fa0-24d1afa55da8.png)
The same grafana instance after login works fine.
Do you have any idea?

**Comment by marcusolsson** [comment]
Yeah, this is a tricky issue. All my plugins check which version of Grafana you're running so that they know what feature are available. The issue is not really that you're not logged in, but that you've probably set [hide_version](https://github.com/grafana/grafana/blob/888683a8ad2f0f05d66d5a5d085c230dbba26e33/conf/defaults.ini#L383) to `true`.

If the plugin don't know the version of Grafana it's running on, it doesn't know what features it can use. The simple solution is to set `hide_version` to `false`, but I assume that there's a reason for hiding it in the first place.

**Comment by mirkocomparetti-synesis** [comment]
Hello,
That is it the case, you are right! For the time being, this is a valid workaround for me.

Thanks!
