### ISSUE TITLE
Date offset

### ISSUE THREAD

**Issue by michaelaeriksen** [marcusolsson/grafana-calendar-panel#44]
I'm trying to use the calendar panel to display some events.

In table view I have this
![image](https://user-images.githubusercontent.com/8325683/165641250-d69ffb6e-58ed-4410-87b3-c0de69e62bdd.png)

But when displayed in the calendar it looks like this
![image](https://user-images.githubusercontent.com/8325683/165641330-f9f85df6-fe6e-43ac-afec-58dc445b4132.png)

As you see there is no data for 2022-04-10 in the table view, but in the calendar view events are put on 2022-04-10.

What am I doing wrong. Is there an offset somewhere for visualizing the data on the calendar I need to set?

**Comment by michaelaeriksen** [comment]
Another thing to note in the image above. The time query is from 2022-04-01 but calendar puts values in 2022-03-31, that seem very odd to me.

**Comment by bcollins-canvas** [comment]
@michaelaeriksen It looks to me like the timestamps in your query are UTC. The calendar is displaying them in localized time. Probably is looks like your data is shifted back a day, because your timezone offset is -7H and your raw data timestamps occur at 00:00:00. The calendar is therefore showing the data as occurring in the days prior because that's actually when they occurred in your local timezone. Can you query in localized time instead of UTC?

**Comment by michaelaeriksen** [comment]
Fixed my query
