### ISSUE TITLE
[Request] Ability to display all events within a day

### ISSUE THREAD

**Issue by Akkarinn** [marcusolsson/grafana-calendar-panel#6]
Hi @marcusolsson 

When within a day there are more events than an hard-coded threshold, a 'more...' line is displayed.
When it happens, we can't see the others raw at all.

It will be really helpfull to be able to expand this 'more ...' line to show the full entries.

Actually, I've updated the related css _overflow_ property to _scroll_ in order to not miss any rows.

**Comment by marcusolsson** [comment]
That's a very reasonable feature :) I think there are several ways to solve this.

- Make each day scrollable instead of displaying the more text
- Display a tooltip when hovering or by clicking
- When clicking the "More" text, the day expand downwards, like a dropdown

One nice feature about the last one is that we could make it expand horizontally to reveal more of the event text as well.

**Comment by Akkarinn** [comment]
Indeed, an horizontal expand would also be something very usefull.
